language: objective-c
os: osx
cache: cocoapods
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
  - RFCI_PRODUCT_NAME="RFSegue"
jobs:
  include:
    - osx_image: xcode11
      env: RFCI_TASK="POD_LINT"
    - osx_image: xcode10
      env: 
      - RFCI_TASK="Xcode10"
      - RFCI_COVERAGE=1
before_install: ./.travis.sh SETUP
script:         ./.travis.sh MAIN
after_success:  ./.travis.sh SUCCESS
after_failure:  ./.travis.sh FAILURE
