language: objective-c
osx_image: xcode9.2
sudo: false
cache: cocoapods
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
  - XB_DEST="platform=iOS Simulator,name=iPhone 6,OS=11.2"
# podfile: Example/Podfile
before_install:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- pod repo update master 
- pod install
script:
- set -o pipefail
- xcodebuild test -enableCodeCoverage YES -workspace RFSegue.xcworkspace -scheme Test-iOS -destination "$XB_DEST" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
after_failure:
 - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
