language: objective-c
osx_image: xcode7.3
cache: cocoapods
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
  - XB_DEST="platform=iOS Simulator,name=iPhone 6,OS=9.0"
# podfile: Example/Podfile
before_install:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- pod install
script:
- set -o pipefail
- xcodebuild test -enableCodeCoverage YES -workspace RFSegue.xcworkspace -scheme Test-iOS -destination "$XB_DEST" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
after_failure:
 - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
